### ISSUE TITLE
Can this tool be applied in TracerSeq?

### ISSUE THREAD

**Issue by xiaozhongshen** [AllonKleinLab/cospar#10]
Hello!
I want to use this tool to analyze the data in the paper (https://www.science.org/doi/10.1126/science.aar4362)
And this paper used the data of TracerSeq. Can you help me to check how to apply this method in analyzing datasets in paper like this?

**Comment by ShouWenWang** [comment]
Hi, 
I would say, in principle, yes, but I have not yet tried that. CoSpar can be used to analyze cumulative barcoding data like tracerSeq. If you can setup the dataset, I am happy to work with you to apply CoSpar there. The first step is to get an anndata object that contains the transcriptome data, and also the barcode data.

**Comment by xiaozhongshen** [comment]
Thanks @ShouWenWang 
Can I send an email to send the CoSpar datasets to you? I am really interested in how to analyze TracerSeq datasets by this method.

**Comment by ShouWenWang** [comment]
Sure. I could not promise to work on this immediately, as I am working on faculty interview these few weeks.  If you send me an email, I can also invite you to a CoSpar slack channel.

**Comment by xiaozhongshen** [comment]
@ShouWenWang  
Thanks! I tried it in the tracerseq. I want to ask one more question. If the time point is only one (24hpf), how can I do the analysis?
