### ISSUE TITLE
CoSpar Memory usage

### ISSUE THREAD

**Issue by jindalk** [AllonKleinLab/cospar#11]
Hi, I am trying to run CoSpar on a dataset with ~80k cells and am constantly running into memory issues (I've tried upto 160GB memory) on the t-map inference step. Do you have any suggestions on how to go about processing a dataset of this size?

EDIT: One possible strategy I am thinking of is running CoSpar in parallel on subsets of my data. Assuming that my clonal data is dense enough to reliably infer a transition map from smaller chunks of my data, can I directly combine fate bias scores obtained from these independent subsets into one large dataset?

Thanks

**Comment by ShouWenWang** [comment]
Hi, Sorry that I missed this message. Yeah, this is currently a limitation of CoSpar. I tried CoSpar on ~49K cells, and it was working fine, although the processing time gets much longer.  

There are several strategies go temporally go around this problem. 
* Using only cells with clonal barcodes. In the case of the LARRY dataset, it has 130K cells, and I removed all non-clonally barcoded cells, and result in 49K cells with at least one clonal barcode.  
* Using only cells from the time points that you are really interested. For example, you are only interested in cell transitions from day 3 to day 29 and day 30, and then you can just pick cells from day 3, 29, and 30. 

You can use a combination of these two strategies.  Please let me know how it goes. I am very happy to help further.

**Comment by jindalk** [comment]
Hi ShouWei, Thanks for your suggestions. I like the idea of removing non-clonal cells but am unsure of whether that would inadvertently introduce any biases. Did you check for that when you subsetted the LARRY data? Anyways, I'll give it a shot and let you know!

**Comment by ShouWenWang** [comment]
It depends on your data type. Is it a re-sampled clonal dataset with clonal observation across multiple time points? In my experience, the result is very robust in this case.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jindalk** [comment]
Yes, it is. Good to know, I'll give it a shot! Thanks
