### ISSUE TITLE
Documentation request -- table to match up paper and software

### ISSUE THREAD

**Issue by ekernf01** [AllonKleinLab/cospar#14]
Hi CoSpar devs! We're using CoSpar in a [class](https://compscbio.github.io/docs/html/index.html) here at Johns Hopkins. We want to make sure we give the students the right instructions or feedback on how to use the software, so I wrote out a short table attempting to connect the English description, the mathematical notation, the function to call, and the output of the function. I'm not able to complete it, and for what I did, I am not sure it is correct. Would you be able to add something like this to your documentation, or provide one-time feedback here? Thanks for considering! It's a really nice project -- technically impressive and useful.

[cospar math.pdf](https://github.com/AllonKleinLab/cospar/files/8420991/cospar.math.pdf)
[cospar math.md](https://github.com/AllonKleinLab/cospar/files/8420989/cospar.math.md)

**Comment by ShouWenWang** [comment]
Hi, here is a quick answer to your questions. Yes, sure, I think it will be useful to document it in the website, and will add it later. 

[cospar.math_sw.pdf](https://github.com/AllonKleinLab/cospar/files/8421546/cospar.math_sw.pdf)
[cospar.math_sw.md](https://github.com/AllonKleinLab/cospar/files/8421547/cospar.math_sw.md)

**Comment by ShouWenWang** [comment]
Here is the table summary.

![Screen Shot 2022-04-05 at 4 58 16 PM](https://user-images.githubusercontent.com/4595786/161848059-4969979a-22e2-4e90-98f2-334d3ad2ad77.jpg)

**Comment by ShouWenWang** [comment]
Here is an updated version. It will appear in the here https://cospar.readthedocs.io/en/latest/getting_started.html

![Screen Shot 2022-04-05 at 5 16 05 PM](https://user-images.githubusercontent.com/4595786/161850620-c3d7b589-4ae5-471a-9507-3ddbc5967b82.jpg)

**Comment by ShouWenWang** [comment]
Correct the color error. 

![Screen Shot 2022-04-05 at 5 20 03 PM](https://user-images.githubusercontent.com/4595786/161851087-140f38f5-b7b5-45d8-9e83-f324ba7307d0.jpg)

**Comment by ShouWenWang** [comment]
Here is an updated version. It will appear in the here https://cospar.readthedocs.io/en/latest/getting_started.html
![Screen Shot 2022-04-05 at 5 32 59 PM](https://user-images.githubusercontent.com/4595786/161853386-04126382-6a9a-4817-b6a8-e5e950977357.jpg)

**Comment by ekernf01** [comment]
Thank you so much! This is terrific!
