### ISSUE TITLE
Does it only apply to the dataset with exogenous cell barcodes?

### ISSUE THREAD

**Issue by sharonyx** [AllonKleinLab/cospar#17]
Hi Shouwen, 
To my understanding, Cospar is designed only for single cells with exogenous cell barcodes. Am I correct? 
As you mentioned, the first step of Cospar is to get an anndata object that contains the transcriptome data. Does the transcriptome data rely on any platform? Or can Cospar be applied to the sing cell RNA seq data generated from different sequencing platforms? Thanks!

**Comment by sharonyx** [comment]
Thanks for your detailed explanation and video recommendation. They helped a lot for Cospar adaption. As long as I have cell-by-gene count matrices from two different time points, I can just try it. Thanks again!

**Comment by krushnapavan9** [comment]
@sharonyx @ShouWenWang  Can we apply if I have cell-by-gene count matrics from only one single time point?

**Comment by ShouWenWang** [comment]
It is possible. But you have to manually split the data into two time points first. This becomes nontrivial, and I have not tested that.

**Comment by ShouWenWang** [comment]
That will be quite challenging. However, you may manually assign earlier and late cell states, and use barcode information from the late cells. Let me know how it goes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
