### ISSUE TITLE
Visualize trees with CoSpar

### ISSUE THREAD

**Issue by ShouWenWang** [AllonKleinLab/cospar#18]
First, after initializing an adata object with X_clone matrix, you can run the following function to construct a tree using neighbor joining

```python
import cospar as cs
cs.tl.fate_hierarchy(adata, source="X_clone")
```

Then, extract the inferred tree with
```python
my_tree_refined = adata.uns["fate_hierarchy_X_clone"]["tree"]
```

Finally, visualize the tree with wrapping function of ete3. To run this you will need to install additional packages
```bash
    conda install -c etetoolkit ete3 ete_toolchain
    pip install PyQt5
    pip install QtPy
```
Now, run this wrap function 
```
cs.pl.visualize_tree(
    my_tree_refined,
    color_coding=None,
    mode="c",
    data_des=f"my_tree",
    figure_path=cs.settings.figure_path,
    dpi=300
)
```

For more information, please look at ete3 package. An example tree:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/4595786/182162182-b6760423-39be-4e57-ab04-3b3936adf036.png">

**Comment by cnk113** [comment]
Hello,

This is a great visualization of the clonal tree, I was wondering if you project multiple levels of metadata like cell_type/cell_subtype/batch etc. like in https://cassiopeia-lineage.readthedocs.io/en/latest/notebooks/local_plotting.html

Thanks,
Chang

**Comment by ShouWenWang** [comment]
Hi,
     This example only shows how to illustrate one metacell information. You have to explore on your own how to add additional information with ete3.

Best regards

Shou-Wen Wang
Postdoc Fellow, Allon Klein Lab
Systems Biology @ Harvard Medical School

________________________________

**Comment by ShouWenWang** [comment]
Thanks for the update. Indeed, this is very tricky!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
