### ISSUE TITLE
Question about input data and transition map inference

### ISSUE THREAD

**Issue by vinothkr11** [AllonKleinLab/cospar#29]
Hi @ShouWenWang, 
Thanks for making this exceptional tool available to the community. I am trying to analyze my lineage tracing data, where the cells are barcoded. I have a couple of questions.

1) I am currently inputting the aggregated data (depth normalized) using cellranger. Would that be okay, or would you prefer no depth normalization? 

2) My dataset has 100k cells, and when I used the HPC cluster to calculate the transition map, it crashed after a few hours. I used your suggestions to reduce my cells to barcoded cells (40k cells) and made it work.  Do you have any suggestions on how to make this work with the entire dataset? I also have cells from one of the three possible states having poor clonal identification towards the end time point, and I am inquisitive about whether that would reduce the data quality. 

Thank you once again. Any suggestions would be appreciated.

**Comment by ShouWenWang** [comment]
Hi,

adata.X: state count matrix, shape (n_cell, n_gene). This should not be log-normalized.
Depth normalization should be OK

Sorry, I have no better suggestions to make it run on the entire dataset, if you could not have larger memory. And I don’t have better clues for your another question.

Finally, the active CoSpar version has migrated to https://github.com/ShouWenWang-Lab/cospar

--
Shou-Wen Wang, Ph.D.
Principal Investigator
School of Life Sciences | School of Science
Westlake University
Shilongshan ST #18, Xihu, Hangzhou, Zhejiang
https://www.shouwenwang-lab.com/



From: Vinothkumar Rajan ***@***.***>
Date: Thursday, June 13, 2024 at 9:20 PM
To: AllonKleinLab/cospar ***@***.***>
Cc: Shouwen WANG 王寿文 ***@***.***>, Mention ***@***.***>
Subject: [AllonKleinLab/cospar] Question about input data and transition map inference (Issue #29)

Hi @ShouWenWang<https://github.com/ShouWenWang>,
Thanks for making this exceptional tool available to the community. I am trying to analyze my lineage tracing data, where the cells are barcoded. I have a couple of questions.

  1.  I am currently inputting the aggregated data (depth normalized) using cellranger. Would that be okay, or would you prefer no depth normalization?
  2.  My dataset has 100k cells, and when I used the HPC cluster to calculate the transition map, it crashed after a few hours. I used your suggestions to reduce my cells to barcoded cells (40k cells) and made it work. Do you have any suggestions on how to make this work with the entire dataset? I also have cells from one of the three possible states having poor clonal identification towards the end time point, and I am inquisitive about whether that would reduce the data quality.

Thank you once again. Any suggestions would be appreciated.

**Comment by vinothkr11** [comment]
Thank you. I will raise a future question in the active Cospar GitHub. One additional question: Does this support parallelization? I currently use 10 nodes at 80 GB RAM per node, but I still end up on the wrong side.

**Comment by ShouWenWang** [comment]
Sorry, I don’t think it supports parallelization.
One fix is to use the smaller datasets with barcodes, and compute the map. Then, merge this data with the cells without barcode, and do some smoothing to propagate the map to the remaining cells.

You can test how much memory is needed to run your 40K data.
For the 130K data, it likely will require 9 times the memory for 40K data.

--
Shou-Wen Wang, Ph.D.
Principal Investigator
School of Life Sciences | School of Science
Westlake University
Shilongshan ST #18, Xihu, Hangzhou, Zhejiang
https://www.shouwenwang-lab.com/



From: Vinothkumar Rajan ***@***.***>
Date: Thursday, June 13, 2024 at 10:25 PM
To: AllonKleinLab/cospar ***@***.***>
Cc: Shouwen WANG 王寿文 ***@***.***>, Mention ***@***.***>
Subject: Re: [AllonKleinLab/cospar] Question about input data and transition map inference (Issue #29)

Thank you. I will raise a future question in the active Cospar GitHub. One additional question: Does this support parallelization? I currently use 10 nodes at 80 GB RAM per node, but I still end up on the wrong side.

**Comment by vinothkr11** [comment]
Thank you, I will give it a try.
