### ISSUE TITLE
Clones different dates

### ISSUE THREAD

**Issue by Shervinhk** [AllonKleinLab/cospar#9]
Hi,

I was checking the HPCs data used in the paper and noticed some clones don't have all of the days (days 2, 4, 6) and many of them miss some of the time points. Can you elaborate on why is that?

**Comment by ShouWenWang** [comment]
Yeah, you are right. Many clones are often observed at a specific date. This is expected from a random sampling of a clone over different time points.

**Comment by ShouWenWang** [comment]
You may find this tweeter tutorial to be useful. 
https://twitter.com/ShouwenW/status/1496375782909923328?s=20&t=RDMO24-4bm3rQNWj5TqHKQ
Particularly, this following image illustrates how clonal resampling works. We are sampling a clone of cells from a founder cell. This clone could have ~10 cells, and they are expanding over time. So, sampling from them, we can get cells from the same clone over time. 

![image](https://user-images.githubusercontent.com/4595786/156651869-450e48ac-1189-48d8-993a-e91261206888.png)
